### ISSUE TITLE
glome-login config file cannot be 'special'

### ISSUE THREAD

**Issue by burgerdev** [google/glome#101]
The range of acceptable config files for `g_key_file_load_from_file` is limited to 'regular' files (as determined by `S_ISREG`), unfortunately excluding a bunch of legitimate config sources:

```shell
$ ./build/login/glome-login -c /dev/null root
ERROR: config file could not be read: Not a regular file

Error: parse-config
$ ./build/login/glome-login -c <(echo -e "[service]\nkey = fee1dead...") root
ERROR: config file could not be read: Not a regular file

Error: parse-config
```

**Comment by pkern** [comment]
This is very weird. It's entirely undocumented but it has been checked for since the first check-in of the parser. I guess it does not matter too much in the real world, because symlinks pointing to regular files are considered regular, but it's still a little unfortunate.
