### ISSUE TITLE
Support more fleet-wide settings in the config file

### ISSUE THREAD

**Issue by burgerdev** [google/glome#122]
It would be convenient if we could set a couple of options that are usually constant in a given deployment environment with the config file. That would allow sharing a `glome-login` binary between environments, and customizing each environment with the config file only. Things that I can think of:

- `hostid-type` (`hostid` would still be obtained from `gethostname(2)`)
- `syslog` config
- timeouts and sleeps
- minimum tag length

**Comment by vvidic** [comment]
Yes, I was planning to add long command line options and also make them available from the config file.

**Comment by burgerdev** [comment]
I would really like to see `hostid-type` support.

**Comment by vvidic** [comment]
Yes, most options should be available in the config now now. So, let me try to add that minimum tag length and host id type.

**Comment by vvidic** [comment]
I think all the mentioned options are added now, so closing this issue!
