### ISSUE TITLE
PAM module arguments naming is inconsistent with the config

### ISSUE THREAD

**Issue by l9i** [google/glome#127]
It would be great if PAM module arguments naming was consistent with the config (and flags in the future once glome-login suports long flags).

Examples of inconsistency:
- `service_key` (PAM) vs `key` (config)
- `service_key_version` (PAM) vs `key-version` (config)
- `url_prefix` (PAM) vs `url-prefix` (config)

Personally, I like the config naming better. It's shorter and uses dashes instead of underscores.

**Comment by pkern** [comment]
I think underscores are also more consistent with other PAM modules, so I'm fine with this. We do have a way to specify a config file as well, right?

**Comment by vvidic** [comment]
Yes, `config_path` can be used to specify the config file.
