### ISSUE TITLE
Provide pam_glome.so (PAM module for GLOME)

### ISSUE THREAD

**Issue by l9i** [google/glome#39]
Implementing a [PAM module](https://en.wikipedia.org/wiki/Pluggable_authentication_module) for GLOME would allow for an easier adoption of GLOME.

**Comment by pkern** [comment]
I think for this we would want to reuse glome-login's configuration and URL generation infrastructure - so maybe glome-login should actually export some kind of library, although I'd argue that a static one is probably better than a shared one.

One thing to test here is conversation support. We would need to display our own prompt and reuse the AUTHTOK as the response to the challenge. This should be possible but relies on the PAM-using application actually being able to display a prompt.

**Comment by pkern** [comment]
I put a skeleton module into [pkern/glome@pam](/pkern/glome/tree/pam).

**Comment by pkern** [comment]
Thanks to Valentin we have a module now! \o/

The other part that I think is still missing is some sort of testing regime. I'm not sure how easy that is with a challenge-response module. [pam_wrapper](https://lwn.net/Articles/671094/) and [fakepam](https://www.eyrie.org/~eagle/software/rra-c-util/fakepam.html) come to mind for testing.

**Comment by vvidic** [comment]
Ah yes, I'll try to add a `pam_test` binary for this.

**Comment by vvidic** [comment]
I suppose we can close this one now the tests are also merged? :)
