### ISSUE TITLE
Clarify glome-login protocol issues

### ISSUE THREAD

**Issue by pkern** [google/glome#62]
Let's use this as an umbrella issue for clarifications that are needed in the glome-login protocol doc.

First off: Make sure we cover how URLs are supposed to be escaped in the protocol documentation.

**Comment by burgerdev** [comment]
- resolve ambiguity of prefix7 (index or, if n/a, prefix) by introducing another explicit variant
- document implications of sending a message tag prefix (i.e. need to pick a longer min tag length for the same security level)

**Comment by burgerdev** [comment]
#60

**Comment by l9i** [comment]
> document implications of sending a message tag prefix (i.e. need to pick a longer min tag length for the same security level)

MAC keys are calculated differently for each direction. Calculating the message tag with the client→server key should not affect the overall security level since authorization relies on the server→client MAC key.

**Comment by burgerdev** [comment]
All identified issues are being addressed in GLOME Login v2.
