### ISSUE TITLE
Reboot action is not authenticated

### ISSUE THREAD

**Issue by vvidic** [google/glome#71]
Starting `glome-login` with the `reboot` username immediately reboots the machine without asking for any authentication.

Not sure if this is expected or not?

**Comment by l9i** [comment]
It is working as designed. The assumption here was that access to a serial console allows for a reboot already (e.g., via SysRq, or physically interacting with a machine) but in any case this this should be properly documented.

**Comment by vvidic** [comment]
PR #72 updates `glome-login` to enable rebooting only if reboot username is explicitly set in the flags.
