### ISSUE TITLE
MVP: Login PAM module plus signing CLI

### ISSUE THREAD

**Issue by pkern** [google/glome#91]
We should actually go and design how glome-login is supposed to be used - with integration into Debian/Ubuntu as an example. I'd suggest the following:

* Users should be able to install a libpam-glome package and the distro scripts would add `pam_glome` to at least the `login` PAM `auth` chain, if not `common-auth`.
* This would do nothing (no failure or error message, `PAM_AUTHINFO_UNAVAIL`?) unless `/etc/glome/config` is found and contains both a service key and a URL prefix - or alternative both are passed via the arguments to the PAM module.
* The PAM module should use `pam_get_authtok` to get the tag, which honors `try_first_pass`. That way we can stack modules properly.
* `pam_glome` should then sort before `pam_unix` (in Debian/Ubuntu-speak its priority for `pam-auth-update` needs to be higher than `unix`'s 256 - `pam_unix` would then automatically gain `try_first_pass`). This would print the GLOME URL and a `Password:` prompt that would accept the tag. If the tag does not validate, PAM would continue with `pam_unix` and check the token as a password.
* This would of course namespace collide tags and passwords, but I think that's an acceptable tradeoff here. Users who do not want password validation can deactivate the password in `/etc/shadow` and `pam_unix` will DTRT.
* My understanding is that such a setup would work with regular terminal-like setups and even SSH - although very likely not with screensavers as the URL would not be displayed properly in that case. Note that the default timeout for `login` on Debian/Ubuntu is 60s - which is a little short for our protocol. We might want to document raising this through `/etc/login.defs`.
* We should have a minimal CLI that actually works with the glome-login protocol rather than just GLOME. The current CLI is kinda weird - it does not even generate the hex keys necessary for glome-login, so you first need to convert them away from binary.
* We could go with `glome login sign`/`tag` - or `glome-login sign`, I don't really care. But it also turns out that we do not have URL decomposition in C yet, which would be somewhat useful to feed URLs into. Basically I think it'd be great to have a CLI that takes the private key file as an argument and parses everything from the `/v1/` to the end and generates the appropriate tag to login with. Additionally there should be commands alike `wg genkey` and `wg pubkey` that DTRT. Then we'd be at the same technical level as Wireguard, where you still need to put those keys into the appropriate places in the config file - although we'd still ship an example config with the keys commented out. Technically this could also be written in a language different from C. I think from a distro point of view I'd weakly prefer it to be Python or C rather than Go.
* We might need to decide if `glome-login` is worth keeping for more minimal environments without PAM.

cc @burgerdev @bluecmd @vvidic @l9i

**Comment by pkern** [comment]
It's probably worth pointing out that @delroth wrote https://github.com/delroth/glome-login-authorize/blob/master/glome-login-authorize.py as a hacky way of generating authorizing tags from the URL.

**Comment by vvidic** [comment]
It seems like `pam-auth-update` only updates `/etc/pam.d/common-*` so it might not be possible to modify `/etc/pam.d/login` (owned by `login` package). Maybe it would be better to ship the module in a disabled state. Admins can than configure and enable it manually only for `login` or use debconf to configure and enable it for all services. For example `/usr/share/pam-configs/yubico`:

```
Name: Yubico authentication with YubiKey
Default: no
Priority: 704
Auth-Type: Primary
Auth:
        required        pam_yubico.so   mode=client try_first_pass id=N key=K
Auth-Initial:
        required        pam_yubico.so   mode=client try_first_pass id=N key=K
```

**Comment by pkern** [comment]
> Admins can than configure and enable it manually only for login or use debconf to configure and enable it for all services.

I'd be fine with that as well - PAM is often something that the local sysadmin needs to configure to their liking. Although to note what we are looking for is effectively using `pam_glome.so` with `sufficient`, so that there are no further checks. `pam_yubico.so` is also [documented in the same way](https://github.com/Yubico/yubico-pam#configuration), so I'm a little surprised about the `required` in the Debian config.

**Comment by vvidic** [comment]
On Fri, May 28, 2021 at 12:29:45PM -0700, Philipp Kern wrote:
> We should actually go and design how glome-login is supposed to be used - with integration into Debian/Ubuntu as an example. I'd suggest the following:
> * We could go with `glome login sign`/`tag` - or `glome-login sign`, I
> don't really care. But it also turns out that we do not have URL
> decomposition in C yet, which would be somewhat useful to feed URLs
> into. Basically I think it'd be great to have a CLI that takes the
> private key file as an argument and parses everything from the `/v1/`
> to the end and generates the appropriate tag to login with.

I have a working `glome login` command in C now, just need to clean it
up a bit and will send for review.

-- 
Valentin

**Comment by vvidic** [comment]
On Fri, May 28, 2021 at 12:29:45PM -0700, Philipp Kern wrote:
> Additionally there should be commands alike `wg genkey` and `wg
> pubkey` that DTRT. Then we'd be at the same technical level as
> Wireguard, where you still need to put those keys into the appropriate
> places in the config file - although we'd still ship an example config
> with the keys commented out. Technically this could also be written in
> a language different from C. I think from a distro point of view I'd
> weakly prefer it to be Python or C rather than Go.

Seems like wg just dumps the key to base64 or hex so that should be
simple enough:

```
#define WG_KEY_LEN_BASE64 ((((WG_KEY_LEN) + 2) / 3) * 4 + 1)
#define WG_KEY_LEN_HEX (WG_KEY_LEN * 2 + 1)

void key_to_base64(char base64[static WG_KEY_LEN_BASE64], const uint8_t key[static WG_KEY_LEN]);
bool key_from_base64(uint8_t key[static WG_KEY_LEN], const char *base64);

void key_to_hex(char hex[static WG_KEY_LEN_HEX], const uint8_t key[static WG_KEY_LEN]);
bool key_from_hex(uint8_t key[static WG_KEY_LEN], const char *hex);

bool key_is_zero(const uint8_t key[static WG_KEY_LEN]);
```

-- 
Valentin

**Comment by burgerdev** [comment]
Looks like we're done here after we get a printable public key, correct?

**Comment by vvidic** [comment]
Also we have till the end of the year to create a package for the next Debian stable release, which should be doable I think.
